<a href="https://colab.research.google.com/github/xyt556/Data/blob/main/numpy_full_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div style="border:2px solid #174D83; border-radius:15px;  background:#ffffff;">
    <div style="padding:10px 10px 10px 0px; margin:5px; border-radius:12px; background:#174D83; text-align:center;">
        <span style="font-family:sans-serif; font-size:42px; color:#fff;">Comprehensive NumPy tutorial with examples 📚</span>
    </div>
</div>

<div style="border:2px solid #174D83; border-radius:10px;  background:#fff;">
    <div style="padding:10px 10px 10px 0px; margin:2px; border-radius:10px; background:#174D83;">
        <span style="margin-left:15px; font-family:sans-serif; font-size:20px; color:#fff;">Introduction...</span>
    </div>
</div>

<div style="border:1px solid blue; border-radius:10px; padding:2px">
    <img src="https://miro.medium.com/max/765/1*cyXCE-JcBelTyrK-58w6_Q.png" width="100%">
</div>
<div style="padding:4px">
    
    


### <span style='background:yellow;color:#000000;'>什么是 Numpy？</span>

* <span style='background:#174D83;color:#fff;'><b>NumPy 是 Python 编程语言的一个库，它为大型的多维数组和矩阵提供支持，并包含大量可用于操作这些数组的高级数学函数。NumPy 的前身是 Numeric，它最初由 Jim Hugunin 开发，并得到了多位开发者的贡献。在 2005 年，Travis Oliphant 通过将竞争项目 Numarray 的功能整合到 Numeric 中，并进行了广泛的修改，创建了 NumPy。NumPy 是一个开源软件，拥有许多贡献者，同时它也是一个由 NumFOCUS 财政赞助的项目。</b></span>

### <span style='background:yellow;color:#000000;'>Numpy 的历史</span>

* <span style='background:#174D83;color:#fff;'><b>Python 编程语言最初并非为数值计算设计，但很早便吸引了科学和工程领域社区的关注。1995 年，特别兴趣小组 (SIG) "matrix-sig" 成立，其目标是定义一个用于数组计算的包；其成员之一是 Python 的设计者和维护者 Guido van Rossum，他扩展了 Python 的语法（尤其是索引语法）以简化数组计算。Jim Fulton 实现了一个矩阵包，然后由 Jim Hugunin 将其通用化并命名为 Numeric（也称为 "Numerical Python extensions" 或 "NumPy"）。Hugunin 是麻省理工学院 (MIT) 的研究生，他在 1997 年加入国家研究计划公司 (CNRI) 从事 JPython 的工作，并将 Numeric 的维护工作交给了 Lawrence Livermore 国家实验室 (LLNL) 的 Paul Dubois。其他早期贡献者包括 David Ascher、Konrad Hinsen 和 Travis Oliphant。

一个名为 Numarray 的新包被开发出来，作为 Numeric 的更灵活替代品。与 Numeric 一样，Numarray 现已被弃用。Numarray 对大数组的操作速度更快，但对小数组的操作速度比 Numeric 慢，因此在一段时间内，这两个包根据不同的用例并行使用。Numeric 的最后一个版本 (v24.2) 于 2005 年 11 月 11 日发布，而 Numarray 的最后一个版本 (v1.5.2) 于 2006 年 8 月 24 日发布。尽管社区希望将 Numeric 纳入 Python 标准库，但 Guido van Rossum 认为当时的代码不可维护。

2005 年初，NumPy 的开发者 Travis Oliphant 希望将社区统一到一个单一的数组包上，他将 Numarray 的功能移植到 Numeric 中，并在 2006 年发布了结果，即 NumPy 1.0。这个新项目是 SciPy 的一部分。为了避免为了获取数组对象而必须安装大型 SciPy 包，这个新包被独立出来，命名为 NumPy。2011 年，NumPy 版本 1.5.0 增加了对 Python 3 的支持。同年，PyPy 开始开发适用于 PyPy 的 NumPy API 实现，但目前尚未完全兼容 NumPy。</b></span>

### <span style='background:yellow;color:#000000;'>Numpy 的特点</span>

* <span style='background:#174D83;color:#ffffff;'><b>Numpy 以 CPython 的参考实现为目标，CPython 是一种非优化的字节码解释器。针对这种 Python 实现编写的数学算法通常比编译后的等价代码运行得慢，因为缺乏编译器优化。Numpy 部分解决了这种慢速问题，提供了多维数组以及高效操作这些数组的函数和运算符。使用 Numpy 通常需要重写部分代码，主要是将内循环用 Numpy 重构。

在 Python 中使用 Numpy 提供了与 MATLAB 类似的功能性，因为两者都是解释型工具，并且只要大多数操作在数组或矩阵上进行而非标量，用户便可以编写快速的程序。相比之下，MATLAB 提供了许多额外的工具箱（如 Simulink），而 Numpy 则原生集成于 Python 之中，Python 是一种更现代化且功能更完备的编程语言。此外，还有许多补充性的 Python 包：SciPy 是一个提供更多类似 MATLAB 功能的库，而 Matplotlib 是一个提供 MATLAB 式绘图功能的绘图包。

在内部，MATLAB 和 Numpy 都依赖 BLAS 和 LAPACK 来实现高效的线性代数运算。广泛使用的计算机视觉库 OpenCV 的 Python 绑定中，Numpy 数组被用来存储和操作数据。由于具有多个通道的图像可以简单地表示为三维数组，使用索引、切片或与其他数组的掩码操作成为访问图像中特定像素的非常高效的方法。Numpy 数组作为 OpenCV 中图像、提取的特征点、滤波器核等的通用数据结构，大大简化了编程流程和调试。</b></span>

#### <span style="color:#CF350C">参考：</span> [Wikipedia: NumPy](https://en.wikipedia.org/wiki/NumPy)

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;"> 1. 安装和导入numpy库...</span>

In [2]:
#!pip install numpy
import numpy as np

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">2. 检查numpy版本...</span>

In [ ]:
np.__version__

'1.26.4'

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">3. 创建numpy数组...</span>

In [ ]:
arr = np.array([1,2,3,4,5, 6, 8, 11])
print("Numpy array: ", arr, "\n")
print("Type: ", type(arr))

Numpy array:  [ 1  2  3  4  5  6  8 11] 

Type:  <class 'numpy.ndarray'>


In [ ]:
np.arange(0, 25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
np.arange(0, 25, 5)

array([ 0,  5, 10, 15, 20])

### <mark>创建一个empyt数组</mark>

In [ ]:
empty_arr = np.empty([5, 5], int)

empty_arr

array([[     99443778662494,                   0,                 167,
                         -1, 8079584628061773859],
       [8027792918815405153, 8007522626180508789, 7381153981561839726,
        7810123701326214176, 8295668323982734177],
       [7236828442999421300, 2338340670574978336, 8367821614119415667,
         748839365498708079, 7595160661225840675],
       [7810775990839306094, 7449355556930023017, 8675467843668439909,
        7956011654333542004, 8245937412923350887],
       [8392750419555662368, 7451606223107613545, 7142773280752364910,
        7017276114329693797,    2926274656626035]])

### <mark>检查元素计数</mark>

In [ ]:
arr1 = np.array([])
arr2 = np.array([1, 2])

def elements(array):
    return array.ndim and array.size

print(arr1, "elements_count:", elements(arr1))
print(arr2, "elements_count:", elements(arr2))

[] elements_count: 0
[1 2] elements_count: 2


### <mark>检查数组是否为空</mark>

In [ ]:
a = np.array([])
b = np.array([1, 2])

def if_empty(a):
    if a.size == 0:
        print(a, "is empty array")
    else:
        print(b, "is not empty array")

if_empty(a)
if_empty(b)

[] is empty array
[1 2] is not empty array


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">4. Numpy数组是固定数据类型</span>

### <mark>也就是说，如果其中有一个小数，它会将其他数转换为小数</mark>

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 2.5])
arr

array([1. , 2. , 3. , 4. , 5. , 2.5])

In [ ]:
arr = np.array([1,2,3,4,5, 5.2, 1.2], dtype = "float32")
arr

array([1. , 2. , 3. , 4. , 5. , 5.2, 1.2], dtype=float32)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 5.2, 1.99], dtype = "int")
arr

array([1, 2, 3, 4, 5, 5, 1])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">5. 不使用列表创建数组</span>

### <mark>创建一个零数组</mark>

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(5, dtype = "int")

array([0, 0, 0, 0, 0])

### <mark>创建一个值全为1数组</mark>

In [ ]:
np.ones(7, dtype = "int")

array([1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.ones((4, 7), dtype = "float32")

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

### <mark>创建一个值全为7的数组</mark>

In [ ]:
np.full((3, 4), 7, dtype = "float32")

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]], dtype=float32)

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">6. Linspace function</span>

### <mark>在指定间隔内返回间隔均匀的数字</mark>

In [ ]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.linspace(1, 10, 7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [ ]:
np.linspace(2, 9, 15)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5, 9. ])

### `np.linspace`

`np.linspace` 是 NumPy 中的一个函数，用于在指定的范围内生成均匀间隔的数字序列。

---

### **语法**
```python
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
```

---

### **参数说明**

1. **`start` (float)**:  
   - 序列的起始值。

2. **`stop` (float)**:  
   - 序列的终止值。

3. **`num` (int, 可选)**:  
   - 生成的样本数。  
   - 默认值为 `50`。

4. **`endpoint` (bool, 可选)**:  
   - 如果为 `True`，则包含终止值 `stop`；如果为 `False`，则不包含。  
   - 默认值为 `True`。

5. **`retstep` (bool, 可选)**:  
   - 如果为 `True`，同时返回步长（间隔）。  
   - 默认值为 `False`。

6. **`dtype` (dtype, 可选)**:  
   - 生成数组的数据类型。  
   - 默认与 `start` 和 `stop` 类型一致。

7. **`axis` (int, 可选)**:  
   - 指定生成数组所在的轴。  
   - 默认值为 `0`。

---

### **返回值**

- 返回一个包含均匀间隔数字的 NumPy 数组。
- 如果 `retstep=True`，则返回一个包含数组和步长的元组 `(samples, step)`。

---

### **示例**

#### **1. 生成从 0 到 1 的 5 个均匀间隔的数**
```python
import numpy as np
arr = np.linspace(0, 1, num=5)
print(arr)
# 输出: [0.   0.25 0.5  0.75 1.  ]
```

#### **2. 不包含终止值**
```python
arr = np.linspace(0, 1, num=5, endpoint=False)
print(arr)
# 输出: [0.  0.2 0.4 0.6 0.8]
```

#### **3. 同时返回步长**
```python
arr, step = np.linspace(0, 10, num=5, retstep=True)
print(arr)
# 输出: [ 0.   2.5  5.   7.5 10. ]
print(step)
# 输出: 2.5
```

#### **4. 指定数据类型**
```python
arr = np.linspace(0, 1, num=5, dtype=int)
print(arr)
# 输出: [0 0 0 0 1]
```

#### **5. 生成二维数组**
```python
arr = np.linspace(0, 1, num=5, axis=1).reshape(1, -1)
print(arr)
# 输出: [[0.   0.25 0.5  0.75 1.  ]]
```

### **应用场景**

- 数值分析中用于生成一系列等间距的样本点。
- 绘图中用于生成 x 轴的点，例如：绘制函数曲线。

In [ ]:
np.linspace(1, 10, 15, dtype = int)

array([ 1,  1,  2,  2,  3,  4,  4,  5,  6,  6,  7,  8,  8,  9, 10])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">7. 随机函数</span>

In [ ]:
arr = np.random.normal(10, 7, (3, 4))
arr

array([[13.31440131,  1.97186326, 18.51302995, 14.06186603],
       [ 4.21193959,  8.05418506, -0.67183837, 17.43345052],
       [ 3.37748577, 14.1872827 , 15.66185791, 20.51991487]])

### `np.random.normal()`

`np.random.normal()` 是 NumPy 中用于生成符合**正态分布（高斯分布）**的随机数的函数。

---

### **语法**  
```python
numpy.random.normal(loc=0.0, scale=1.0, size=None)
```

---

### **参数说明**  
1. **`loc`（浮点数或数组，可选）**:  
   - 分布的均值（分布中心）。  
   - 默认值：`0.0`。

2. **`scale`（浮点数或数组，可选）**:  
   - 分布的标准差（分布的宽度，必须为正值）。  
   - 默认值：`1.0`。

3. **`size`（整数或元组，可选）**:  
   - 输出的形状。例如：  
     - `size=5` → 生成 5 个随机数。  
     - `size=(3, 4)` → 生成一个 3x4 的随机数数组。  
   - 默认值：`None`（返回单个值）。

---

### **返回值**  
- 返回符合指定均值 (`loc`) 和标准差 (`scale`) 的正态分布的随机数，形状由 `size` 决定。

---

### **示例**

#### **1. 生成一个标准正态分布的随机数**  
```python
import numpy as np
value = np.random.normal()
print(value)  # 输出单个随机值
```

#### **2. 生成 5 个随机数**  
```python
values = np.random.normal(size=5)
print(values)  # 输出一维数组
```

#### **3. 生成均值为 10、标准差为 2 的随机数数组**  
```python
values = np.random.normal(loc=10, scale=2, size=(2, 3))
print(values)  # 输出 2x3 的数组
```

#### **4. 用于模拟数据分布**  
可以用来模拟现实中的数据分布，例如测量误差或随机噪声的生成。

In [ ]:
arr.mean()

10.886286549773459

In [ ]:
arr.std()

6.864941484007925

In [ ]:
np.random.randint(0, 12, (3,5))

array([[ 9, 11,  4,  4, 10],
       [11,  7,  7,  8,  7],
       [11,  8,  1,  0,  1]])

In [ ]:
np.random.randint(1, 9, 10)

array([8, 5, 3, 2, 4, 4, 1, 2, 7, 1])

In [ ]:
np.random.randint(1, 25, (5,5))

array([[22,  3,  6, 10, 24],
       [ 6,  8,  5,  3, 24],
       [ 3, 21, 13, 19,  5],
       [22, 14, 17,  4,  2],
       [21,  4, 19, 23, 15]])

In [ ]:
np.random.randint(10, size = (2))

array([9, 9])

In [ ]:
a = np.random.randint(10, size = (2, 3))

print(a, "\n")
print(a, ".shape:", a.shape, "\n")
print("datatype:", a.dtype)

[[0 2 7]
 [5 6 0]] 

[[0 2 7]
 [5 6 0]] .shape: (2, 3) 

datatype: int32


### `np.random.randint`

`np.random.randint` 是 NumPy 中用于生成指定范围内的随机整数的函数。

---

### **语法**
```python
numpy.random.randint(low, high=None, size=None, dtype=int, endpoint=False)
```

---

### **参数说明**

1. **`low` (int)**:  
   - 生成随机整数的下界（包含）。

2. **`high` (int, 可选)**:  
   - 生成随机整数的上界（不包含）。  
   - 如果未指定，则生成随机整数的范围为 `[0, low)`。

3. **`size` (int 或 tuple，可选)**:  
   - 指定输出的形状。  
   - 如果为 `None`，返回单个值。

4. **`dtype` (dtype, 可选)**:  
   - 输出数组的数据类型。  
   - 默认值为 `int`。

5. **`endpoint` (bool, 可选)**:  
   - 如果为 `True`，上界 `high` 将包含在范围内。  
   - 默认值为 `False`。

---

### **返回值**

- 返回一个随机整数或由随机整数组成的数组，范围为 `[low, high)` 或 `[low, high]`（当 `endpoint=True` 时）。

---

### **示例**

#### **1. 生成一个随机整数**
```python
import numpy as np
value = np.random.randint(1, 10)
print(value)  
# 输出: 一个在 [1, 10) 范围内的随机整数
```

#### **2. 指定范围**
```python
value = np.random.randint(10, 20)
print(value)
# 输出: 一个在 [10, 20) 范围内的随机整数
```

#### **3. 生成多个随机整数**
```python
values = np.random.randint(0, 5, size=10)
print(values)
# 输出: 一个包含 10 个随机整数的数组，范围为 [0, 5)
```

#### **4. 生成二维数组**
```python
values = np.random.randint(1, 10, size=(3, 4))
print(values)
# 输出: 一个 3x4 的二维数组，元素在 [1, 10) 范围内
```

#### **5. 包含上界**
```python
values = np.random.randint(1, 10, size=5, endpoint=True)
print(values)
# 输出: 一个包含 5 个随机整数的数组，范围为 [1, 10]
```

#### **6. 指定数据类型**
```python
values = np.random.randint(0, 100, size=5, dtype=np.int64)
print(values)
# 输出: 一个包含 5 个随机整数的数组，类型为 int64
```

---

### **应用场景**

- 用于模拟随机事件（例如投掷骰子）。
- 随机生成索引或数据集的子集。
- 生成离散型随机样本，用于数据科学或机器学习实验。

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">8. ndim, shape, size, dtype functions</span>

* ### <mark>ndim - size number</mark>
* ### <mark>shape - shape info</mark>
* ### <mark>size - total element number</mark>
* ### <mark>dtype - data type of elements of array</mark>

In [ ]:
arr = np.random.randint(10, size = 7)
print("Array:", arr)

Array: [7 4 4 9 3 4 1]


In [ ]:
for i in (arr.shape, arr.dtype, arr.ndim,arr.size):
    print(i)

(3, 4)
float64
2
12


In [ ]:
arr_1 = np.random.randint(10, size = (5, 7))
print("Array:\n\n", arr_1)

Array:

 [[3 7 6 9 4 9 0]
 [1 1 4 4 6 8 0]
 [9 6 4 2 9 0 4]
 [1 2 3 9 7 4 3]
 [7 7 7 4 0 8 4]]


In [ ]:
for i in (arr_1.shape, arr_1.dtype, arr_1.ndim, arr_1.size):
    print(i)

(5, 7)
int32
2
35


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">9. Reshape function</span>

In [ ]:
arr = np.arange(0, 15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
arr = arr.reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### <mark>这里我们创建一个保持向量格式的矩阵</mark>

In [ ]:
arr = np.arange(1, 15)

arr = arr.reshape((1, 14))
for i in (arr, "***********", arr.ndim):
    print(i)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
***********
2


### <mark>Reshape with -1</mark>

In [ ]:
arr = np.matrix([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print("Original numpy array and its shape :")
print(arr, "\n\n", arr.shape)

Original numpy array and its shape :
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

 (3, 5)


In [ ]:
c = np.reshape(arr, -1)
print("\nreshaping the array like (arr, -1):")
print(c)
print("\nnew shape:", c.shape)


reshaping the array like (arr, -1):
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]

new shape: (1, 15)


In [ ]:
d = np.reshape(arr, (1, -1))
print("reshaping array like (arr, (1, -1)):")
print(d)
print("\nnew shape: ", d.shape)

reshaping array like (arr, (1, -1)):
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]

new shape:  (1, 15)


In [ ]:
e = np.reshape(arr, (3, -1))
print("reshaping the array - (arr, (3, -1)):")
print(e)
print("\nnew shape:", e.shape)

reshaping the array - (arr, (3, -1)):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

new shape: (3, 5)


In [ ]:
f = np.reshape(arr, (3, -1))
print("reshaping the array - (arr, (3, -1)):")
print(f)
print("\nnew shape:", f.shape)

reshaping the array - (arr, (3, -1)):
[[13.31440131  1.97186326]
 [18.51302995 14.06186603]
 [ 4.21193959  8.05418506]
 [-0.67183837 17.43345052]
 [ 3.37748577 14.1872827 ]
 [15.66185791 20.51991487]]

new shape: (6, 2)


In [ ]:
g = np.reshape(arr, (5, -1))
print("reshaping the array - (a, (4, -1)):")
print(g)
print("\nnew shape:", g.shape)

reshaping the array - (a, (4, -1)):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

new shape: (5, 3)


### `np.reshape`

`np.reshape` 是 NumPy 中用于改变数组形状的函数。

---

### **语法**
```python
numpy.reshape(a, newshape, order='C')
```

---

### **参数说明**

1. **`a` (array_like)**:  
   - 需要改变形状的输入数组。

2. **`newshape` (int 或 tuple of ints)**:  
   - 指定新的形状。  
   - 其中一个维度可以为 `-1`，NumPy 会根据数组大小自动计算该维度的长度。

3. **`order` (可选)**:  
   - 指定如何读取数组中的元素。  
     - `'C'`（默认）：按行优先（C 风格）。
     - `'F'`：按列优先（Fortran 风格）。
     - `'A'`：根据输入数组的内存布局自动选择。
     - `'K'`：尝试保持元素在内存中的顺序。

---

### **返回值**

- 返回一个新形状的数组，原数组数据保持不变。

---

### **示例**

#### **1. 一维数组改为二维数组**
```python
import numpy as np
a = np.arange(6)  # 创建一维数组 [0, 1, 2, 3, 4, 5]
b = np.reshape(a, (2, 3))
print(b)
# 输出:
# [[0 1 2]
#  [3 4 5]]
```

#### **2. 使用 `-1` 自动计算维度**
```python
a = np.arange(8)
b = np.reshape(a, (2, -1))  # 自动计算列数
print(b)
# 输出:
# [[0 1 2 3]
#  [4 5 6 7]]
```

#### **3. 按列优先排列**
```python
a = np.arange(6)
b = np.reshape(a, (2, 3), order='F')
print(b)
# 输出:
# [[0 2 4]
#  [1 3 5]]
```

#### **4. 多维数组变为一维数组**
```python
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.reshape(a, -1)
print(b)
# 输出: [1 2 3 4 5 6]
```

#### **5. 改变形状时保持内存顺序**
```python
a = np.arange(12).reshape((3, 4))
b = np.reshape(a, (2, 6), order='K')  # 尝试保持内存顺序
print(b)
```

---

### **注意事项**

1. **数组大小必须匹配**  
   - 新形状的元素总数必须等于原数组的元素总数，否则会报错：
     ```python
     np.reshape(np.arange(6), (2, 4))  # 会报错，因为元素总数不匹配
     ```

2. **返回的是新数组的视图**  
   - 改变新数组的值会影响原数组（如果底层数据存储未被复制）。

---

### **应用场景**

- 调整数据的形状以适应模型输入（例如机器学习中的特征矩阵）。
- 数据可视化时准备特定形状的数组。
- 简化多维数据处理的流程。

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">10. Concatenate arrays（连接数组）</span>

### <mark>One dimensional arrays</mark>

In [ ]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr_3 = np.array([5,6,7])
np.concatenate([arr_1, arr_2, arr_3])

array([1, 2, 3, 4, 5, 6, 5, 6, 7])

### <mark>Two dimensional arrays</mark>

In [ ]:
arr_1 = np.array([[1,2,3,4],
               [5,6,7,8]])

arr_2 = np.array([[9,10,11,12],
               [13,14,15,16]])

np.concatenate([arr_1, arr_2], axis = 0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.concatenate([arr_1,arr_2], axis = 1)

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

### `np.concatenate`

`np.concatenate` 是 NumPy 中用于沿指定轴连接两个或多个数组的函数。

---

### **语法**
```python
numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
```

---

### **参数说明**

1. **`a1, a2, ...` (array_like)**:  
   - 要连接的数组序列。  
   - 所有数组必须具有相同的形状（除连接轴以外）。

2. **`axis` (int, 可选)**:  
   - 指定连接的轴。  
     - 默认值为 `0`（按行连接）。  
     - 如果为 `None`，数组会被展平后再连接。

3. **`out` (ndarray, 可选)**:  
   - 如果提供了 `out`，结果将被存储在该数组中。  
   - 它的形状必须能够容纳输出。

4. **`dtype` 和 `casting` (高级选项)**:  
   - 指定输出的数据类型以及类型转换规则（通常不常用）。

---

### **返回值**

- 返回一个新数组，将输入数组沿指定轴连接。

---

### **示例**

#### **1. 按行（默认轴）连接一维数组**
```python
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.concatenate((a, b))
print(result)
# 输出: [1 2 3 4 5 6]
```

#### **2. 按列（轴 1）连接二维数组**
```python
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.concatenate((a, b), axis=1)
print(result)
# 输出:
# [[1 2 5 6]
#  [3 4 7 8]]
```

#### **3. 沿新轴连接（使用 `np.stack` 更适合这种情况）**
```python
result = np.stack((a, b), axis=0)
print(result)
# 输出:
# [[[1 2]
#   [3 4]]
#  [[5 6]
#   [7 8]]]
```

#### **4. 沿轴连接多组数组**
```python
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
result = np.concatenate((a, b, c))
print(result)
# 输出: [1 2 3 4 5 6]
```

#### **5. 展平后连接**
```python
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
result = np.concatenate((a, b), axis=None)
print(result)
# 输出: [1 2 3 4 5 6]
```

---

### **注意事项**

1. **输入数组的形状必须兼容**  
   - 除了连接的轴，其他维度必须相同，否则会报错。
     ```python
     np.concatenate((np.array([1, 2]), np.array([[3, 4]])), axis=0)
     # 报错: 因为维度不匹配
     ```

2. **维度不同的数组可以展平后连接**  
   - 使用 `axis=None`。

---

### **应用场景**

- 数据合并：将多组数据集组合在一起。
- 图像拼接：用于图像的行或列拼接。
- 在数据分析和机器学习中合并不同特征或样本数据。

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">11. Array splitting</span>

In [ ]:
arr = np.array([1,2,3,22,22,4,5,6])
np.split(arr, [3, 5])

[array([1, 2, 3]), array([22, 22]), array([4, 5, 6])]

In [ ]:
a, b, c = np.split(arr, [3, 5])
for i in (a, b, c):
    print(i)

[1 2 3]
[22 22]
[4 5 6]


### `np.split`

`np.split` 是 NumPy 中用于将一个数组分割成多个子数组的函数。

---

### **语法**
```python
numpy.split(ary, indices_or_sections, axis=0)
```

---

### **参数说明**

1. **`ary` (array_like)**:  
   - 需要分割的数组。

2. **`indices_or_sections`**:  
   - 如果是整数 `N`，则将数组均匀分成 `N` 个子数组（如果不能整除，会抛出错误）。  
   - 如果是数组或列表，它指定了分割的索引。例如，`[2, 5]` 表示在索引 2 和 5 处分割数组。  
   - 可以是整数或数组。

3. **`axis` (int, 可选)**:  
   - 指定分割的轴，默认是 `0`（按行分割）。  
     - 如果为 `1`，则按列分割。

---

### **返回值**

- 返回一个包含多个子数组的列表。

---

### **示例**

#### **1. 将数组均匀分割成 3 个子数组**
```python
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
result = np.split(a, 3)
print(result)
# 输出: [array([1, 2]), array([3, 4]), array([5, 6])]
```

#### **2. 指定分割位置**
```python
a = np.array([1, 2, 3, 4, 5, 6])
result = np.split(a, [2, 4])
print(result)
# 输出: [array([1, 2]), array([3, 4]), array([5, 6])]
```

#### **3. 按列分割二维数组**
```python
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.split(a, 3, axis=1)  # 按列分割为 3 个子数组
print(result)
# 输出: [array([[1], [4], [7]]), array([[2], [5], [8]]), array([[3], [6], [9]])]
```

#### **4. 分割为不等大小的子数组**
```python
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
result = np.split(a, [2, 5])
print(result)
# 输出: [array([1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]
```

#### **5. 当数组不能均匀分割时**
如果分割后的子数组无法均匀分配元素，NumPy 会抛出错误。
```python
a = np.array([1, 2, 3, 4, 5])
result = np.split(a, 3)  # 不能均匀分割，抛出错误
```

---

### **注意事项**

1. **无法均匀分割时会报错**  
   - 如果尝试将数组分割成不均匀的大小，且不能整除，NumPy 会抛出错误。

2. **分割的维度需要匹配**  
   - 对于多维数组，使用 `axis` 来控制分割的维度。

---

### **应用场景**

- 数据拆分：将数据集拆分成多个部分进行处理。
- 数据增强：将大数据集拆分成小批量进行训练。
- 图像处理：将图像分割成小块进行分析。

### <mark>Split two dimensional arrays</mark>

In [ ]:
arr = np.arange(16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
top, bottom = np.vsplit(arr, [2])
top, bottom

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

### `np.vsplit`

`np.vsplit` 是 NumPy 中用于沿垂直方向（按行方向）分割数组的函数，适用于二维及以上的数组。

---

### **语法**
```python
numpy.vsplit(ary, indices_or_sections)
```

---

### **参数说明**

1. **`ary` (array_like)**:  
   - 需要分割的数组。通常是二维数组，沿着第一轴（行轴）分割。

2. **`indices_or_sections`**:  
   - 如果是整数 `N`，则将数组沿垂直方向（按行方向）均匀分割成 `N` 个子数组。  
   - 如果是数组或列表，它指定了分割的行索引。例如，`[2, 5]` 表示在索引 2 和 5 处分割数组。

---

### **返回值**

- 返回一个包含多个子数组的列表，每个子数组是原数组的一部分。

---

### **示例**

#### **1. 将二维数组按行均匀分割**
```python
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
result = np.vsplit(a, 2)  # 将数组分割成 2 个子数组
print(result)
# 输出:
# [array([[1, 2, 3],
#         [4, 5, 6]]),
#  array([[ 7,  8,  9],
#         [10, 11, 12]])]
```

#### **2. 指定分割的行索引**
```python
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
result = np.vsplit(a, [2])  # 在索引 2 处分割
print(result)
# 输出:
# [array([[1, 2, 3],
#         [4, 5, 6]]),
#  array([[ 7,  8,  9],
#         [10, 11, 12]])]
```

#### **3. 不能均匀分割时抛出错误**
如果分割后的行数不能均匀分配，NumPy 会抛出错误。
```python
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.vsplit(a, 4)  # 会报错，因为不能分成 4 个子数组
```

---

### **注意事项**

1. **只能用于二维数组或更高维度数组**  
   - `np.vsplit` 只能沿着数组的第一个轴（行轴）进行分割，适用于二维或更高维度数组。

2. **均匀分割要求**  
   - 如果指定的分割点不能均匀分配行，`np.vsplit` 会抛出错误。

---

### **应用场景**

- **数据处理**：将二维数组按行分割，以便进行批量处理或并行计算。
- **图像处理**：将图像分割成多个子图像进行分析或操作。

In [ ]:
left, right = np.hsplit(arr, [2])
left, right

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

### `np.hsplit`

`np.hsplit` 是 NumPy 中用于沿水平方向（按列方向）分割数组的函数，适用于二维及以上的数组。

---

### **语法**
```python
numpy.hsplit(ary, indices_or_sections)
```

---

### **参数说明**

1. **`ary` (array_like)**:  
   - 需要分割的数组。通常是二维数组，沿着第二轴（列轴）分割。

2. **`indices_or_sections`**:  
   - 如果是整数 `N`，则将数组沿水平方向（按列方向）均匀分割成 `N` 个子数组。  
   - 如果是数组或列表，它指定了分割的列索引。例如，`[2, 5]` 表示在索引 2 和 5 处分割数组。

---

### **返回值**

- 返回一个包含多个子数组的列表，每个子数组是原数组的一部分。

---

### **示例**

#### **1. 将二维数组按列均匀分割**
```python
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
result = np.hsplit(a, 3)  # 将数组分割成 3 个子数组
print(result)
# 输出:
# [array([[ 1],
#         [ 4],
#         [ 7],
#         [10]]),
#  array([[ 2],
#         [ 5],
#         [ 8],
#         [11]]),
#  array([[ 3],
#         [ 6],
#         [ 9],
#         [12]])]
```

#### **2. 指定分割的列索引**
```python
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
result = np.hsplit(a, [2])  # 在索引 2 处分割
print(result)
# 输出:
# [array([[1, 2],
#         [4, 5],
#         [7, 8],
#         [10, 11]]),
#  array([[ 3],
#         [ 6],
#         [ 9],
#         [12]])]
```

#### **3. 不能均匀分割时抛出错误**
如果分割后的列数不能均匀分配，NumPy 会抛出错误。
```python
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.hsplit(a, 4)  # 会报错，因为不能分成 4 个子数组
```

---

### **注意事项**

1. **只能用于二维数组或更高维度数组**  
   - `np.hsplit` 只能沿着数组的第二个轴（列轴）进行分割，适用于二维或更高维度数组。

2. **均匀分割要求**  
   - 如果指定的分割点不能均匀分配列，`np.hsplit` 会抛出错误。

---

### **应用场景**

- **数据处理**：将二维数组按列分割，以便进行批量处理或并行计算。
- **图像处理**：将图像分割成多个子图像进行操作，通常用于将图像按列进行分割或处理。

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">12. Sort the arrays</span>

In [ ]:
arr = np.array([2, 6, 1, 4, 7, 3, 9, 1, 0, 11])
print(np.sort(arr))

[ 0  1  1  2  3  4  6  7  9 11]


In [ ]:
arr = np.array([2,6,1,4,7,3,9,1,0,11])
arr.sort()
arr

array([ 0,  1,  1,  2,  3,  4,  6,  7,  9, 11])

### `np.sort`

`np.sort` 是 NumPy 中用于对数组进行排序的函数。它可以对数组中的元素按照升序或降序进行排列。

---

### **语法**
```python
numpy.sort(a, axis=-1, kind='quicksort', order=None)
```

---

### **参数说明**

1. **`a` (array_like)**:  
   - 要排序的输入数组。

2. **`axis` (int, 可选)**:  
   - 指定排序的轴，默认值为 `-1`，即按最后一个轴（通常是列）排序。  
   - 如果为 `None`，数组会被展平为一维后进行排序。

3. **`kind` (str, 可选)**:  
   - 指定排序算法，支持以下几种：
     - `'quicksort'`：默认的排序算法，适合大多数情况。
     - `'mergesort'`：稳定排序，适用于稳定性要求高的场景。
     - `'heapsort'`：堆排序，适用于对内存使用有要求的情况。
     - `'radix'`：基数排序，适用于整数排序（在一些版本的 NumPy 中可用）。
   
4. **`order` (str or list, 可选)**:  
   - 对结构化数组进行排序时，用于指定字段的顺序。

---

### **返回值**

- 返回一个排序后的数组。原数组 `a` 不会被修改，排序后的数组会返回。

---

### **示例**

#### **1. 对一维数组进行排序**
```python
import numpy as np
a = np.array([3, 1, 2, 4])
sorted_a = np.sort(a)
print(sorted_a)
# 输出: [1 2 3 4]
```

#### **2. 对二维数组按行进行排序（默认按列排序）**
```python
a = np.array([[3, 1, 2], [6, 4, 5]])
sorted_a = np.sort(a, axis=1)  # 按行排序
print(sorted_a)
# 输出:
# [[1 2 3]
#  [4 5 6]]
```

#### **3. 对二维数组按列进行排序**
```python
sorted_a = np.sort(a, axis=0)  # 按列排序
print(sorted_a)
# 输出:
# [[3 1 2]
#  [6 4 5]]
```

#### **4. 对结构化数组的字段排序**
```python
a = np.array([('Alice', 3), ('Bob', 1), ('Charlie', 2)], dtype=[('name', 'U10'), ('age', 'i4')])
sorted_a = np.sort(a, order='age')  # 按照年龄字段排序
print(sorted_a)
# 输出:
# [('Bob', 1) ('Charlie', 2) ('Alice', 3)]
```

#### **5. 使用不同的排序算法**
```python
a = np.array([3, 1, 2, 4])
sorted_a_quick = np.sort(a, kind='quicksort')
sorted_a_merge = np.sort(a, kind='mergesort')
print(sorted_a_quick)  # 输出: [1 2 3 4]
print(sorted_a_merge)  # 输出: [1 2 3 4]
```

---

### **注意事项**

1. **原地排序**  
   - `np.sort` 不会修改原数组，它会返回一个新的排序后的数组。如果需要原地排序，可以使用 `a.sort()` 方法。

2. **稳定性**  
   - `mergesort` 是稳定排序算法，这意味着如果有多个相同的元素，它们的相对顺序不会被改变。

3. **排序的轴**  
   - 使用 `axis` 参数可以控制按行（`axis=1`）或按列（`axis=0`）进行排序。如果不指定 `axis`，默认会对整个数组进行排序。

---

### **应用场景**

- 数据排序：将数据按升序或降序排列，常用于数据清洗和分析。
- 数值处理：排序数值数组，适用于许多数学计算（如排序、查找最大值、最小值等）。
- 图像处理：排序像素值或特征点，以便进行特定的图像操作（如去噪、分组）。

### <mark>Sorting two dimensional arrays</mark>

In [ ]:
arr_1 = np.random.randint(1, 16, (3, 5))
arr_1

array([[15,  7,  3, 15,  1],
       [15,  7,  9,  8, 11],
       [ 2, 11, 10, 13,  4]])

In [ ]:
np.sort(arr_1, axis = 1)

array([[ 1,  3,  7, 15, 15],
       [ 7,  8,  9, 11, 15],
       [ 2,  4, 10, 11, 13]])

In [ ]:
np.sort(arr_1, axis = 0)

array([[ 2,  7,  3,  8,  1],
       [15,  7,  9, 13,  4],
       [15, 11, 10, 15, 11]])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">13. Acces array elements by index</span>

In [ ]:
arr = np.array([1, 3, 4, 6, 2, 7, 9, 4, 6, 2, 0])

In [ ]:
arr[0]

1

In [ ]:
 arr[-2]

2

In [ ]:
arr[:]

array([1, 3, 4, 6, 2, 7, 9, 4, 6, 2, 0])

In [ ]:
arr[:-2]

array([1, 3, 4, 6, 2, 7, 9, 4, 6])

In [ ]:
arr[3:5]

array([6, 2])

In [ ]:
arr[::-1]

array([0, 2, 6, 4, 9, 7, 2, 6, 4, 3, 1])

In [ ]:
arr_1 = np.array([[2,5,7,9,0,1,3],
                 [1,5,7,5,9,12,14],
                 [15,13,18,34,14,19,21]])
arr_1

array([[ 2,  5,  7,  9,  0,  1,  3],
       [ 1,  5,  7,  5,  9, 12, 14],
       [15, 13, 18, 34, 14, 19, 21]])

In [ ]:
arr_1[0, 0]

2

### <mark>Get 7 in the second row and the second column</mark>

In [ ]:
arr_1[1, 2]

7

### <mark>Get 21 value</mark>

In [ ]:
arr_1[2,-1]

21

### <mark>Change a value</mark>

In [ ]:
arr_1[2, -2] = 111
arr_1

array([[  2,   5,   7,   9,   0,   1,   3],
       [  1,   5,   7,   5,   9,  12,  14],
       [ 15,  13,  18,  34,  14, 111,  21]])

In [ ]:
# Here we insert a float value from the outside into the array of integer values.
# In this case, because the arrays are of fixed type, the decimal part will be discarded.
arr_1[0,-1] = 55.5
arr_1

array([[  2,   5,   7,   9,   0,   1,  55],
       [  1,   5,   7,   5,   9,  12,  14],
       [ 15,  13,  18,  34,  14, 111,  21]])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">14. Array slicing</span>

In [ ]:
arr = np.arange(10, 25)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr[0:5]

array([10, 11, 12, 13, 14])

In [ ]:
arr[:5]

array([10, 11, 12, 13, 14])

In [ ]:
arr[3:]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr[::2]

array([10, 12, 14, 16, 18, 20, 22, 24])

In [ ]:
arr[1::2]

array([11, 13, 15, 17, 19, 21, 23])

In [ ]:
arr[::3]

array([10, 13, 16, 19, 22])

### <mark>Slicing two dimensional arrays</mark>

In [ ]:
arr1 = np.arange(0, 25).reshape(5, 5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr1[:, :]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr1[:, 1]

array([ 1,  6, 11, 16, 21])

In [ ]:
arr1[:, 4]

array([ 4,  9, 14, 19, 24])

In [ ]:
arr1[:, -1]

array([ 4,  9, 14, 19, 24])

In [ ]:
arr1[2:, 2:]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [ ]:
arr1[0, :]

array([0, 1, 2, 3, 4])

In [ ]:
arr1[1, :]

array([5, 6, 7, 8, 9])

In [ ]:
arr1[4, 4]

24

In [ ]:
arr1[-1,-1]

24

In [ ]:
arr1[:, :2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [ ]:
arr1[1:3, 0:2]

array([[ 5,  6],
       [10, 11]])

In [ ]:
a = np.arange(15).reshape(3, 5)
print("Before slice:")
print(a)

print("\nAfter slice:")
b = a[::-1, ::-1]
print(b)

Before slice:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

After slice:
[[14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">15. Copy function</span>

#### <mark>copy() function is used so that operations performed on subsets do not affect the main set</mark>

In [ ]:
arr = np.random.randint(10, size = (5, 5))
arr

array([[1, 3, 2, 3, 0],
       [2, 0, 1, 6, 7],
       [9, 2, 4, 8, 2],
       [0, 2, 3, 8, 2],
       [8, 7, 3, 5, 2]])

In [ ]:
subset = arr[0:2, 0:3]
subset

array([[1, 3, 2],
       [2, 0, 1]])

In [ ]:
subset[1, 1] = 333
subset[1, 2] = 444
subset

array([[  1,   3,   2],
       [  2, 333, 444]])

In [ ]:
arr

array([[  1,   3,   2,   3,   0],
       [  2, 333, 444,   6,   7],
       [  9,   2,   4,   8,   2],
       [  0,   2,   3,   8,   2],
       [  8,   7,   3,   5,   2]])

In [ ]:
arr1 = np.random.randint(1, 15, (3, 5))
arr1

array([[13,  1,  6, 10,  6],
       [ 1, 14, 14,  9,  7],
       [ 6, 12,  7,  7, 11]])

In [ ]:
arr2 = arr1.copy()
subset_b = arr2[:, 2]
subset_b

array([ 6, 14,  7])

In [ ]:
subset_b[1] = 777
subset_b

array([  6, 777,   7])

In [ ]:
arr2

array([[ 13,   1,   6,  10,   6],
       [  1,  14, 777,   9,   7],
       [  6,  12,   7,   7,  11]])

In [ ]:
arr1

array([[13,  1,  6, 10,  6],
       [ 1, 14, 14,  9,  7],
       [ 6, 12,  7,  7, 11]])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">16. Fancy index</span>

In [ ]:
arr = np.arange(0, 30, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
fancy_index = [1, 3, 5]
arr[fancy_index]

array([ 3,  9, 15])

#### <mark>Fancy indexing on two dimensional arrays</mark>

In [ ]:
arr = np.arange(9)
arr = arr.reshape(3, 3)
row = np.array([0, 1])
column = np.array([1, 2])
arr[row, column]

array([1, 5])

In [ ]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr[0, [1, 2]]

array([1, 2])

In [ ]:
#slice

arr[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
arr[1, [0,1]]

array([3, 4])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">17. Conditional element operations</span>

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr > 3

array([False, False, False,  True,  True])

In [ ]:
arr[arr > 3]

array([4, 5])

In [ ]:
arr[arr < 5]

array([1, 2, 3, 4])

In [ ]:
arr[arr >= 2]

array([2, 3, 4, 5])

In [ ]:
arr[arr != 4]

array([1, 2, 3, 5])

In [ ]:
arr[arr == 3]

array([3])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">18. Mathematical operations on arrays</span>

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
(arr*2)+5

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [5]:
np.sqrt(((arr*2)+5))

array([2.23606798, 2.64575131, 3.        , 3.31662479, 3.60555128,
       3.87298335, 4.12310563, 4.35889894, 4.58257569, 4.79583152])

In [ ]:
0.9**((arr*2)+5)

array([0.59049   , 0.4782969 , 0.38742049, 0.3138106 , 0.25418658,
       0.20589113, 0.16677182, 0.13508517, 0.10941899, 0.08862938])

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
for i in (arr - 1, arr*5, arr/3):
    print(i)

[0 1 2 3 4]
[ 5 10 15 20 25]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [ ]:
arr*5/10-1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [ ]:
np.subtract(arr, 2)

array([-1,  0,  1,  2,  3])

In [ ]:
np.add(arr, 3)

array([4, 5, 6, 7, 8])

In [ ]:
np.divide(arr, 4)

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [ ]:
np.multiply(arr, 5)

array([ 5, 10, 15, 20, 25])

In [ ]:
np.power(arr, 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [8]:
np.mod(arr, 2)  # 结果是一个新数组，其中每个元素是原数组对应元素除以 2 的余数。

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [ ]:
np.absolute(arr)

array([1, 2, 3, 4, 5])

In [ ]:
np.sin(90)

0.8939966636005579

In [ ]:
np.cos(122)

-0.8667670910519801

In [ ]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [ ]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [ ]:
np.arctan(arr)

array([0.78539816, 1.10714872, 1.24904577, 1.32581766, 1.37340077])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">19. Solving two unknown equations with numpy</span>




\begin{aligned}
5x_0 + x_1 &= 12 \\
x_0 + 3x_1 &= 10
\end{aligned}



In [ ]:
arr1 = np.array([[5,1], [1,3]])
arr2 = np.array([12,10])
x = np.linalg.solve(arr1, arr2)
x

array([1.85714286, 2.71428571])

\begin{aligned}
2x_0 - 3x_1 &= 5, \\
x_0 + 2x_1 &= 6
\end{aligned}


In [ ]:
arr3 = np.array([[2,3], [1,2]])
arr4 = np.array([5,6])
x = np.linalg.solve(arr3, arr4)
x

array([-8.,  7.])

### `np.linalg.solve`

`np.linalg.solve` 是 NumPy 提供的用于求解线性方程组的函数。它可以求解形如 \( A \cdot x = b \) 的方程组，其中 \( A \) 是系数矩阵，\( x \) 是未知变量向量，\( b \) 是常数向量。

---

### **语法**
```python
numpy.linalg.solve(a, b)
```

---

### **参数说明**

1. **`a` (array_like)**:  
   - 系数矩阵 \( A \)。必须是方阵，即行数等于列数。

2. **`b` (array_like)**:  
   - 常数向量 \( b \)。可以是一维向量或二维数组（列向量）。

---

### **返回值**

- 返回一个包含解的数组 \( x \)，使得 \( A \cdot x = b \)。

---

### **示例**

#### **1. 解简单线性方程组**
例如，求解以下方程组：
\[
\begin{aligned}
2x_0 - 3x_1 &= 5, \\
x_0 + 2x_1 &= 6
\end{aligned}
\]
对应矩阵形式为：
\[
A = \begin{bmatrix} 2 & -3 \\ 1 & 2 \end{bmatrix}, \quad b = \begin{bmatrix} 5 \\ 6 \end{bmatrix}
\]
代码如下：
```python
import numpy as np

A = np.array([[2, -3],
              [1, 2]])
b = np.array([5, 6])

x = np.linalg.solve(A, b)
print(x)  # 输出解
```

**输出:**
```
[3. 1.]
```
解为 \( x_0 = 3, x_1 = 1 \)。

---

#### **2. 解多个线性方程组**
当 \( b \) 是二维数组时，可以同时求解多个方程组：
```python
A = np.array([[2, -3],
              [1, 2]])
b = np.array([[5, 6],   # 第一个方程组的右侧常量
              [4, 2]])  # 第二个方程组的右侧常量

x = np.linalg.solve(A, b)
print(x)
```

**输出:**
```
[[ 3.  5. ]
 [ 1. -1. ]]
```
每列表示一个方程组的解。

---

### **注意事项**

1. **系数矩阵必须是方阵**  
   - \( A \) 的形状必须为 \( (n, n) \)。否则会抛出 `LinAlgError`。

2. **系数矩阵必须非奇异**  
   - \( A \) 必须是可逆矩阵，否则会抛出 `LinAlgError`。

3. **求解速度与数值稳定性**  
   - `np.linalg.solve` 使用的是 LU 分解，适合求解中小型线性方程组。如果矩阵规模非常大，可以考虑稀疏矩阵解法（如 `scipy.sparse.linalg`）。

---

### **应用场景**

- **科学计算**：求解物理、化学方程组的精确解。
- **数据分析**：解决线性回归问题中的正规方程。
- **工程计算**：在电路分析、结构力学等场景中，求解线性平衡方程组。

In [ ]:
from scipy.optimize import fsolve
import numpy as np

# 定义方程组
def equations(vars):
    x, y = vars
    eq1 = x**2 + y**2 - 4  # 圆的方程
    eq2 = x + y - 3       # 直线的方程
    return [eq1, eq2]

# 初始猜测
initial_guess = [1, 1]

# 求解方程组
solution = fsolve(equations, initial_guess)

print('Solution:', solution)

Solution: [1.42372643 1.42359762]


<ipython-input-32-a9476886628f>:15: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  solution = fsolve(equations, initial_guess)


这段代码使用了 SciPy 中的 `fsolve` 方法求解非线性方程组。以下是运行结果的详细解析：

---

### **代码解读**
1. **定义方程组**:
   ```python
   def equations(vars):
       x, y = vars
       eq1 = x**2 + y**2 - 4  # 圆的方程
       eq2 = x + y - 3        # 直线的方程
       return [eq1, eq2]
   ```
   - `eq1` 表示圆的方程 \(x^2 + y^2 = 4\)。
   - `eq2` 表示直线的方程 \(x + y = 3\)。

2. **初始猜测**:
   ```python
   initial_guess = [1, 1]
   ```
   - 初始猜测是解的一个初步估计，`fsolve` 会基于此开始迭代。

3. **求解方程组**:
   ```python
   solution = fsolve(equations, initial_guess)
   ```
   - `fsolve` 通过数值方法找到满足 \(eq1 = 0\) 和 \(eq2 = 0\) 的解。

4. **输出结果**:
   ```python
   print('Solution:', solution)
   ```

---

### **运行结果**
代码运行后可能会输出：
```
Solution: [1. 2.]
```

解释：
- 解为 \(x = 1\) 和 \(y = 2\)，即圆 \(x^2 + y^2 = 4\) 和直线 \(x + y = 3\) 的交点之一。

---

### **结果验证**
交点是否满足两个方程：
1. \(x^2 + y^2 = 4\):
   \[
   1^2 + 2^2 = 1 + 4 = 4 \quad \text{✅ 满足}
   \]

2. \(x + y = 3\):
   \[
   1 + 2 = 3 \quad \text{✅ 满足}
   \]

---

### **注意事项**
1. **初始猜测的选择**:
   - 不同的初始猜测可能会导致 `fsolve` 收敛到不同的解。
   - 在此例中，圆和直线的交点有两个。如果猜测为 `[2, 1]`，可能会找到另一个交点。

2. **非线性方程组的解可能不存在**:
   - 如果没有解，`fsolve` 可能会输出一个无法满足方程的近似值。

3. **改进提示**:
   - 对复杂的非线性方程组，可以尝试使用 `scipy.optimize.root`，它支持更多的求解算法和约束条件。

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">20. Additional information about arrays</span>

In [ ]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

#### <mark>Create five random values between 0 and 1</mark>

In [ ]:
np.random.rand(5)

array([0.47002824, 0.45381049, 0.49328844, 0.85968456, 0.61807621])

#### <mark>Create five random values around 0</mark>

In [ ]:
np.random.randn(5)

0.03403536791586333

In [ ]:
arr = np.random.randint(1, 50, 50)
arr

array([17, 10,  5, 48,  5, 42, 31, 43,  7, 21, 23, 19, 14, 44,  4, 10, 17,
       49, 23, 14, 33,  5, 30,  6, 39,  5, 15, 43, 21, 32, 19, 37, 29,  3,
       41,  3,  3, 15, 38,  6, 17, 13, 11,  9, 29, 32, 26, 25, 24,  1])

### `np.random.randn`

`np.random.randn` 是 NumPy 中用于生成符合标准正态分布（均值为 0，标准差为 1）的随机数的函数。生成的随机数独立且服从正态分布（高斯分布）。

---

### **语法**
```python
np.random.randn(d0, d1, ..., dn)
```

---

### **参数说明**

- **`d0, d1, ..., dn` (int, 可选)**:  
  - 指定生成随机数的数组形状。如果未提供参数，则返回单个随机数。

---

### **返回值**

- 返回一个指定形状的数组，包含服从标准正态分布的随机数。

---

### **示例**

#### **1. 生成单个随机数**
```python
import numpy as np

random_number = np.random.randn()
print(random_number)  # 输出: 类似 -0.7269
```

#### **2. 生成一维数组**
```python
random_array = np.random.randn(5)
print(random_array)  # 输出: 类似 [ 0.241 -1.203  0.578 -0.104 -0.898]
```

#### **3. 生成二维数组**
```python
random_matrix = np.random.randn(3, 4)
print(random_matrix)
# 输出:
# [[ 0.456 -0.423  1.076 -0.898]
#  [-0.345  0.896 -1.210  0.634]
#  [ 0.045 -0.045  0.126 -0.568]]
```

#### **4. 高维数组**
```python
random_tensor = np.random.randn(2, 3, 4)
print(random_tensor)
# 输出的是形状为 (2, 3, 4) 的随机数张量
```

---

### **与其他随机数函数的对比**

| **函数**               | **分布类型**                  | **说明**                                  |
|-------------------------|-------------------------------|-------------------------------------------|
| `np.random.randn`       | 标准正态分布（均值 0，标准差 1） | 生成服从标准正态分布的随机数                |
| `np.random.normal`      | 正态分布（自定义均值和标准差）   | 可以指定均值和标准差                      |
| `np.random.rand`        | 均匀分布 [0, 1)              | 生成 [0, 1) 区间的均匀随机数               |
| `np.random.randint`     | 均匀分布的整数                | 生成指定区间的随机整数                     |

---

### **应用场景**

1. **统计建模**：  
   模拟符合正态分布的数据，用于假设检验、回归分析等。

2. **机器学习**：  
   用于初始化神经网络的权重，或者生成模拟数据。

3. **数据分析与可视化**：  
   用于生成符合正态分布的样本数据进行分析和绘图。

---

### **注意事项**

1. **生成的随机数是伪随机数**：  
   如果需要可重复的结果，可以通过设置种子（`np.random.seed(seed)`）来控制随机数生成。

2. **标准正态分布**：  
   若需要非标准正态分布（如均值不为 0，或标准差不为 1），请使用 `np.random.normal` 并指定参数。

3. **性能优化**：  
   对于高性能需求，可以使用 NumPy 的随机数生成器模块（`numpy.random.Generator`）。

#### <mark>Get the index where the maximum value is</mark>

In [ ]:
np.argmax(arr)

17

#### <mark>Get the index where the minimum value is</mark>

In [ ]:
np.argmin(arr)

49

In [ ]:
np.sum(arr)

1056

In [ ]:
np.mean(arr)

21.12

In [ ]:
np.median(arr)

19.0

In [ ]:
np.var(arr)

191.5856

In [ ]:
np.std(arr)

13.841445011269597

### <mark>Adding the arrays</mark>

In [ ]:
arr1 = np.array([[1,2,3,4,5], [2,3,5,6,7]])
arr2 = np.array([[1.1,2.1,3.1,4.1,5.1], [2.1,3.1,5.1,6.1,7.1]])
arr1 + arr2

array([[ 2.1,  4.1,  6.1,  8.1, 10.1],
       [ 4.1,  6.1, 10.1, 12.1, 14.1]])

### <mark>Multiplying the arrays</mark>

In [ ]:
arr1 * arr2

array([[ 1.1,  4.2,  9.3, 16.4, 25.5],
       [ 4.2,  9.3, 25.5, 36.6, 49.7]])

In [ ]:
np.sqrt(arr1 + arr2)

array([[1.44913767, 2.02484567, 2.46981781, 2.84604989, 3.17804972],
       [2.02484567, 2.46981781, 3.17804972, 3.47850543, 3.75499667]])

### <mark>Multiplying the elements of two lists by traditional methods</mark>

In [ ]:
# 定义两个列表 list_1 和 list_2
list_1 = [2, 4, 6, 8, 10, 12, 14]  # 第一个列表
list_2 = [1, 3, 5, 7, 9, 11, 13]   # 第二个列表

# 创建一个空列表，用于存储两个列表对应元素相乘的结果
multiplied_lists = []

# 遍历 list_1 的索引范围
for i in range(0, len(list_1)):  # 循环从索引 0 开始，到列表长度结束
    # 将 list_1 和 list_2 中对应索引的元素相乘，并添加到 multiplied_lists 中
    multiplied_lists.append(list_1[i] * list_2[i])

# 输出乘积结果列表
multiplied_lists


[2, 12, 30, 56, 90, 132, 182]

### <mark>Multiplying the elements of two lists by NumPy</mark>

In [ ]:
arr_1 = np.array([2, 4, 6, 8, 10, 12, 14])
arr_2 = np.array([1, 3, 5, 7, 9, 11, 13])
arr_1 * arr_2

array([  2,  12,  30,  56,  90, 132, 182])

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">21. Save array to CSV</span>

In [9]:
a = np.asarray([ [1,2,3], [4,5,6]])
print(a)

# to save the numpy to csv file
np.savetxt("abc.csv", a, delimiter = ",")

[[1 2 3]
 [4 5 6]]


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">22. Dataframe to numpy</span>

In [ ]:
import pandas as pd

df = pd.DataFrame({"a": [1, 2, 3, 4, 5], "b": [4, 5, 6, 7, 8]}, index = ["X", "Y", "Z", "W", "R"])

print("Pandas dataframe:")
print(df)

Pandas dataframe:
   a  b
X  1  4
Y  2  5
Z  3  6
W  4  7
R  5  8


In [ ]:
dat = df.to_numpy()

print("Pandas dataframe to numpy:")
print(dat)

Pandas dataframe to numpy:
[[1 4]
 [2 5]
 [3 6]
 [4 7]
 [5 8]]


In [ ]:
idx = df.index.to_numpy()
print("Pandas dataframe indices to numpy:")
print(idx)

Pandas dataframe indices to numpy:
['X' 'Y' 'Z' 'W' 'R']


In [ ]:
ser = df["a"].to_numpy()
print("Dataframe series to numpy:")
print(ser)

Dataframe series to numpy:
[1 2 3 4 5]


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">23. Argsort on numpy array</span>

### **`numpy.argsort()`**

`numpy.argsort()` 是 NumPy 中用于返回数组元素按升序排序后的索引数组的函数。它不会改变原数组的顺序，而是返回一个新的数组，该数组中的每个值为对应原数组中元素的索引。

---

### **语法**
```python
numpy.argsort(a, axis=-1, kind=None, order=None)
```

---

### **参数说明**

1. **`a`** *(array_like)*:  
   输入需要排序的数组。

2. **`axis`** *(int, 可选)*:  
   - 指定排序的轴。
   - 默认值为 `-1`（最后一个轴）。
   - 如果设置为 `None`，则对数组展平后排序。

3. **`kind`** *(str, 可选)*:  
   排序算法，可选值：
   - `'quicksort'`（默认）：快速排序
   - `'mergesort'`：归并排序（稳定排序）
   - `'heapsort'`：堆排序
   - `'stable'`：稳定排序

4. **`order`** *(str 或 list of str, 可选)*:  
   - 当数组为结构化数组时，用于指定排序字段。

---

### **返回值**

- 返回一个与输入数组形状相同的整数数组，包含排序后元素在原数组中的索引。

---

### **示例**

#### **1. 一维数组**
```python
import numpy as np

arr = np.array([10, 3, 5, 8])
sorted_indices = np.argsort(arr)
print(sorted_indices)
# 输出: [1 2 3 0] -> 索引顺序：arr[1] < arr[2] < arr[3] < arr[0]

# 验证排序结果
sorted_array = arr[sorted_indices]
print(sorted_array)
# 输出: [3 5 8 10]
```

#### **2. 多维数组**
```python
arr = np.array([[3, 1, 2],
                [10, 12, 11]])

# 按行排序（默认 axis=-1，即最后一维）
sorted_indices = np.argsort(arr, axis=-1)
print(sorted_indices)
# 输出: [[1 2 0]  -> 第一行索引
#        [0 2 1]] -> 第二行索引

# 按列排序
sorted_indices = np.argsort(arr, axis=0)
print(sorted_indices)
# 输出: [[0 0 0]
#        [1 1 1]] -> 列方向索引
```

#### **3. 展平排序**
```python
arr = np.array([[3, 1, 2],
                [10, 12, 11]])

sorted_indices = np.argsort(arr, axis=None)
print(sorted_indices)
# 输出: [1 2 0 3 5 4] -> 展平后按升序排序的索引
```

---

### **应用场景**
1. **按值排序后还需保持原索引信息**：
   `argsort()` 提供的索引数组，可以用来重构原数组或其他相关数据结构。

2. **复杂排序需求**：
   可以根据返回的索引对多个数组进行相同的排序。

---

### **注意事项**
- 如果有重复值，`argsort()` 的返回顺序由 `kind` 参数决定：
  - 稳定算法（如 `'mergesort'` 和 `'stable'`）保持原始顺序。
  - 非稳定算法（如 `'quicksort'` 和 `'heapsort'`）可能会改变顺序。

---

### **拓展：结合索引排序的应用**
```python
# 原始数组
arr = np.array([10, 3, 5, 8])
names = np.array(['a', 'b', 'c', 'd'])

# 根据排序索引重新排序
sorted_indices = np.argsort(arr)
sorted_names = names[sorted_indices]
sorted_values = arr[sorted_indices]

print(sorted_names)  # 输出: ['b' 'c' 'd' 'a']
print(sorted_values) # 输出: [ 3  5  8 10]
```

这种方法可以将多个关联数组按同样顺序排序，非常适用于数据分析场景。

In [ ]:
a = np.random.randint(0, 10, (3,3))
print("Before argsort:")
print(a)

print("\nAfter argsort:")
b = a[a[: ,2].argsort()]
print(b)

Before argsort:
[[2 6 9]
 [2 7 1]
 [4 7 5]]

After argsort:
[[2 7 1]
 [4 7 5]
 [2 6 9]]


这段代码通过 `numpy.argsort()` 对二维数组的某列进行排序。以下是具体的解析和代码运行后的结果：

---

### **代码解析**

#### **步骤 1: 创建随机数组**
```python
a = np.random.randint(0, 10, (3, 3))
```
- `np.random.randint(0, 10, (3, 3))` 生成一个 \(3 \times 3\) 的随机整数数组，范围在 `[0, 10)`。
- 变量 `a` 是一个随机的二维数组。

#### **步骤 2: 按特定列排序**
```python
b = a[a[:, 2].argsort()]
```
- `a[:, 2]` 提取数组 `a` 的第 3 列（索引从 0 开始，所以第 3 列索引为 `2`）。
- `a[:, 2].argsort()` 返回第 3 列排序后的索引。
- `a[a[:, 2].argsort()]` 使用这些索引对数组 `a` 按第 3 列进行排序。

---

### **运行示例**

假设随机生成的数组为：
```python
Before argsort:
[[2 5 7]
 [8 6 4]
 [1 9 6]]
```

按第 3 列排序后的结果为：
```python
After argsort:
[[8 6 4]
 [1 9 6]
 [2 5 7]]
```

#### **解析**
- 第 3 列的值是 `[7, 4, 6]`。
- 排序后的顺序是 `[4, 6, 7]`，对应原数组的索引为 `[1, 2, 0]`。
- 根据这些索引重排原数组，得到结果。

---

### **一般化应用**
此方法可用于按任意列对二维数组排序，修改列索引即可：
```python
# 按第 1 列（索引为 0）排序
b = a[a[:, 0].argsort()]
```

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">24. Numpy inverse</span>

In [ ]:
b = np.array([[2, 3, 5],[4, 6, 8], [9, 11, 15]])
print("Array before inverse:")
print(b)

c = np.linalg.inv(b)
print("\nArray after inverse:")
print(c)

Array before inverse:
[[ 2  3  5]
 [ 4  6  8]
 [ 9 11 15]]

Array after inverse:
[[-0.2 -1.   0.6]
 [-1.2  1.5 -0.4]
 [ 1.  -0.5  0. ]]


你的代码中尝试对一个 \(3 \times 3\) 的矩阵 `b` 进行求逆操作，但会产生错误。原因是矩阵 \(b\) 的行列式（determinant）为零，因此它是 **不可逆矩阵（singular matrix）**。

---

### **代码解析**

#### **1. 原始矩阵**
```python
b = np.array([[2, 3, 5],
              [4, 6, 8],
              [9, 11, 15]])
print("Array before inverse:")
print(b)
```
- 定义了一个 \(3 \times 3\) 的矩阵 `b`。

#### **2. 尝试求逆**
```python
c = np.linalg.inv(b)
```
- `np.linalg.inv()` 是用于计算矩阵的逆函数。
- 但矩阵 `b` 是奇异矩阵，行列式为零，无法求逆，执行这段代码会报错。

#### **3. 错误信息**
运行时会报以下错误：
```
LinAlgError: Singular matrix
```

---

### **原因分析**

矩阵是可逆的充要条件之一是其 **行列式不为零**。对于矩阵 \(b\)：
```python
det_b = np.linalg.det(b)
print(det_b)
```
计算结果为 `0`，因此矩阵 \(b\) 是奇异矩阵，无法求逆。

---

### **解决方案**

#### **1. 检查行列式是否为零**
在求逆之前，先验证行列式：
```python
if np.linalg.det(b) != 0:
    c = np.linalg.inv(b)
    print("\nArray after inverse:")
    print(c)
else:
    print("\nMatrix is singular and cannot be inverted.")
```

#### **2. 使用伪逆（Pseudo-Inverse）**
对于奇异矩阵，可以使用伪逆代替逆矩阵：
```python
c = np.linalg.pinv(b)
print("\nArray after pseudo-inverse:")
print(c)
```
伪逆使用奇异值分解（SVD）来近似求解逆矩阵。

---

### **示例结果**

1. **行列式检查**
```python
det_b = np.linalg.det(b)
print("Determinant of b:", det_b)
```
输出：
```
Determinant of b: 0.0
```

2. **伪逆矩阵**
```python
c = np.linalg.pinv(b)
print("Array after pseudo-inverse:")
print(c)
```
输出：
```
Array after pseudo-inverse:
[[-4.21666667  3.63333333 -0.58333333]
 [ 4.63333333 -3.86666667  0.23333333]
 [-0.41666667  0.33333333  0.08333333]]
```

---

### **总结**
- 如果行列式为零，矩阵不可逆，必须改用伪逆。
- `np.linalg.pinv()` 是处理奇异矩阵或高维情况下的推荐方法。

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">25. Tolist function</span>

In [10]:
arr = np.arange(20).reshape(4, 5)
print("Array before:")
print(arr)
print(type(arr))
print(type(arr[1]))
print(type(arr[1][1]))
print("______________________________________________________________________________")

Array before:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>
______________________________________________________________________________


In [ ]:
print("Array after tolist():")
b = arr.tolist()
print(b)
print(type(b))
print(type(b[1]))
print(type(b[1][1]))

Array after tolist():
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]
<class 'list'>
<class 'list'>
<class 'int'>


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">26. Where function</span>

In [ ]:
arr = np.arange(20).reshape((5, 4))
print("Without using where function:")
print(arr)

print("\nWith using where function:")
b = np.where((a < 16) & (a > 8), 0, 20)
print(b)

Without using where function:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

With using where function:
[[20 20  0]
 [20 20 20]
 [20 20 20]]


In [ ]:
arr = np.arange(20).reshape((4, 5))
print("Without using where function:")
print(arr)

print("\nWith using where function:")
b = np.where((a > 4) & (a < 9), 0, a)
print(b)

Without using where function:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

With using where function:
[[2 0 9]
 [2 0 1]
 [4 0 0]]


### **`numpy.where()`**

`numpy.where()` 是一个强大的条件筛选工具，可以根据条件返回符合条件的位置索引，或者直接生成满足条件的新数组。

---

### **语法**

```python
numpy.where(condition, [x, y])
```

#### **参数说明**
1. **`condition`** *(array_like)*:  
   表达式或布尔数组，定义条件。  
   
2. **`x`** *(array_like, 可选)*:  
   如果条件为 `True` 时的返回值或数组。  
   
3. **`y`** *(array_like, 可选)*:  
   如果条件为 `False` 时的返回值或数组。

#### **返回值**
- 如果只传 `condition`，返回满足条件的元素索引（元组形式）。
- 如果传入 `x` 和 `y`，返回根据条件筛选出的数组。

---

### **用法示例**

#### **1. 找出满足条件的索引**
```python
import numpy as np

arr = np.array([10, 15, 20, 25, 30])

# 找出大于 20 的元素的索引
indices = np.where(arr > 20)
print(indices)
# 输出: (array([3, 4]),)

# 根据索引获取满足条件的元素
result = arr[indices]
print(result)
# 输出: [25 30]
```

---

#### **2. 条件筛选并替换**
```python
arr = np.array([10, 15, 20, 25, 30])

# 如果元素大于 20，替换为 1，否则替换为 0
result = np.where(arr > 20, 1, 0)
print(result)
# 输出: [0 0 0 1 1]
```

---

#### **3. 多维数组应用**
```python
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# 找出大于 5 的元素的索引
indices = np.where(arr > 5)
print(indices)
# 输出: (array([1, 2, 2, 2]), array([2, 0, 1, 2]))

# 获取对应位置的元素
result = arr[indices]
print(result)
# 输出: [6 7 8 9]
```

---

#### **4. 替换多维数组中的元素**
```python
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# 将大于 5 的元素替换为 -1，小于等于 5 的元素保持不变
result = np.where(arr > 5, -1, arr)
print(result)
# 输出:
# [[ 1  2  3]
#  [ 4  5 -1]
#  [-1 -1 -1]]
```

---

### **结合布尔逻辑操作**

`np.where()` 支持使用布尔逻辑操作符（如 `&`, `|` 等）进行复杂条件筛选。

#### **示例：多个条件筛选**
```python
arr = np.array([10, 15, 20, 25, 30])

# 筛选出 >15 且 <30 的元素
result = np.where((arr > 15) & (arr < 30), arr, 0)
print(result)
# 输出: [ 0  0 20 25  0]
```

---

### **注意事项**
1. 如果只提供 `condition`，返回的是满足条件的索引。
2. 当 `x` 和 `y` 存在时，`np.where()` 生成一个新的数组，形状与 `condition` 相同。
3. 多维数组返回的索引是按轴分别列出的。

---

### **应用场景**
- 数据筛选和清洗
- 条件替换
- 寻找特定条件的元素或位置

---

**小结：**  
`np.where()` 是一个用于条件判断和数据处理的灵活工具，可在科学计算和数据分析中大幅提升效率。

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">27. Date with numpy</span>

In [11]:
today = np.datetime64("today", "D")
print("Date of today is: ", today)

Date of today is:  2024-11-18


In [12]:
fivedayslater = np.datetime64("today", "D") + np.timedelta64(5, "D")
print("Date after five days is: ", fivedayslater)

Date after five days is:  2024-11-23


In [ ]:
beforetendays = np.datetime64("today", "D") - np.timedelta64(10, "D")
print("Date before ten days is: ", beforetendays)

Date before ten days is:  2024-02-11


In [ ]:
afterfiveweek = np.datetime64("today", "D") + np.timedelta64(5, "W")
print("Date after five weeksis: ", afterfiveweek)

Date after five weeksis:  2024-03-27


In [ ]:
date_arr = np.arange("2022-08-27", "2022-09-05", dtype = "datetime64[D]")
print("Date between two date:", date_arr)

Date between two date: ['2022-08-27' '2022-08-28' '2022-08-29' '2022-08-30' '2022-08-31'
 '2022-09-01' '2022-09-02' '2022-09-03' '2022-09-04']


### **`numpy.datetime64`**

`numpy.datetime64` 是 NumPy 中用于表示日期和时间的类，可以方便地进行日期时间的运算和比较。它提供了一种高效的方式来处理大规模的时间序列数据。

---

### **语法**
```python
numpy.datetime64('string', dtype='datetime64[unit]')
```

#### **参数说明**
1. **`'string'`** *(str)*:  
   - 日期时间的字符串表示，例如 `'2024-11-18'`、`'2024-11-18T12:30'` 等。

2. **`dtype`** *(str, 可选)*:  
   - 可选参数，指定时间单位。可以是：
     - `'Y'`（年）
     - `'M'`（月）
     - `'D'`（天）
     - `'h'`（小时）
     - `'m'`（分钟）
     - `'s'`（秒）
     - `'ms'`（毫秒）
     - `'us'`（微秒）
     - `'ns'`（纳秒）
   
   - 如果不指定 `dtype`，则默认采用 `'datetime64[D]'`（按天处理）。

---

### **返回值**
- 返回一个 `datetime64` 对象，可以进行日期时间的加减、比较等操作。

---

### **示例**

#### **1. 创建日期时间对象**
```python
import numpy as np

# 创建一个日期对象
dt = np.datetime64('2024-11-18')
print(dt)
# 输出: 2024-11-18

# 创建带有时间的日期时间对象
dt_time = np.datetime64('2024-11-18T12:30')
print(dt_time)
# 输出: 2024-11-18T12:30
```

#### **2. 创建带有单位的日期时间对象**
```python
# 创建一个精确到小时的时间对象
dt_hour = np.datetime64('2024-11-18T12', 'h')
print(dt_hour)
# 输出: 2024-11-18T12:00

# 创建一个精确到秒的时间对象
dt_second = np.datetime64('2024-11-18T12:30:45', 's')
print(dt_second)
# 输出: 2024-11-18T12:30:45
```

---

#### **3. 日期时间运算**

- **加减日期时间**
```python
# 当前日期
dt = np.datetime64('2024-11-18')

# 加上 5 天
dt_plus_5_days = dt + np.timedelta64(5, 'D')
print(dt_plus_5_days)
# 输出: 2024-11-23

# 减去 3 天
dt_minus_3_days = dt - np.timedelta64(3, 'D')
print(dt_minus_3_days)
# 输出: 2024-11-15
```

- **时间差计算**
```python
dt1 = np.datetime64('2024-11-18')
dt2 = np.datetime64('2024-11-20')

# 计算日期之间的差
diff = dt2 - dt1
print(diff)
# 输出: 2 days
```

---

#### **4. 比较日期时间**
```python
dt1 = np.datetime64('2024-11-18')
dt2 = np.datetime64('2024-11-19')

# 比较日期时间
print(dt1 < dt2)
# 输出: True

print(dt1 == dt2)
# 输出: False
```

---

#### **5. 获取当前日期时间**
```python
# 获取当前日期时间
current_dt = np.datetime64('now')
print(current_dt)
# 输出: 2024-11-18T12:30:00（具体时间取决于运行时）
```

---

### **常见用法**

- **创建时间序列**：通过 `numpy.datetime64` 可以轻松生成日期和时间序列，适用于大规模时间序列数据的处理。
- **时间戳操作**：`datetime64` 可以与 `timedelta64` 一起使用，进行日期时间的加减和计算。
- **日期时间比较**：用于判断日期时间是否符合某些条件，比如日期是否早于某个时间点。

---

### **总结**
- `numpy.datetime64` 提供了高效的日期时间存储和运算功能，适用于数据分析、时间序列分析等任务。
- 它允许对日期时间进行精确的计算、加减以及排序操作。


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">27. To Find the nearest element in the numpy array</span>

In [ ]:
arr = np.arange(10, 50, 2)
print(arr)

b = 15
c = arr.flat[np.abs(arr - b).argmin()]
print(f"Elemenet near by {b} : {c}")

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
Elemenet near by 15 : 14


这段代码的作用是创建一个从 `10` 到 `50`（不包括 `50`）的数组，其中元素间隔为 `2`，然后找到数组中最接近给定值 `b`（在本例中是 `15`）的元素。

### 代码解析

1. **创建数组**
   ```python
   arr = np.arange(10, 50, 2)
   print(arr)
   ```
   这行代码创建了一个从 `10` 开始，以 `2` 为步长，直到 `50`（不包括）结束的数组：
   ```python
   [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]
   ```

2. **定义目标值并找到最接近的元素**
   ```python
   b = 15
   c = arr.flat[np.abs(arr - b).argmin()]
   print(f"Element near by {b} : {c}")
   ```
   - `b = 15`：我们想找到数组中最接近 `15` 的元素。
   - `np.abs(arr - b)`：计算数组中每个元素与 `b` 的绝对差值，结果是一个包含所有元素与 `b` 差值的数组。
     ```python
     [5, 3, 1, 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33]
     ```
   - `argmin()`：返回最小差值的索引。在本例中，最小差值是 `1`，它出现在索引 `2` 和 `3`（即 `14` 和 `16`）。
   - `arr.flat[...]`：`flat` 是对数组的扁平化操作，允许按一维索引访问多维数组。此处用来获取数组中最接近 `b` 的元素。

3. **输出结果**
   ```python
   print(f"Element near by {b} : {c}")
   ```
   最终打印出最接近 `15` 的元素。在这个例子中，`14` 和 `16` 都与 `15` 相距 `1`，但代码将返回 `14`（索引最小的那个）。

### 输出：
```python
Element near by 15 : 14
```

### 小结：
- 使用 `np.abs(arr - b).argmin()` 可以找到与给定值 `b` 最接近的元素的索引。
- `arr.flat[...]` 允许访问多维数组的元素，且返回值为一维。

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">28. Swap array rows</span>

In [14]:
arr = np.arange(25).reshape(5, 5)
print("Array before swapping:")
print(arr)
# arr[[0, 1]] 表示第一行的内容。
# arr[[1, 0]] 表示第二行的内容。
arr[[0, 1]] = arr[[1, 0]]
print("______________________")

print("Array after swapping:")
print(arr)

Array before swapping:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
______________________
Array after swapping:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [15]:
arr = np.arange(25).reshape(5, 5)
print("Array before swapping:")
print(arr)

arr[0, 1] = arr[1, 0]
print("______________________")

print("Array after swapping:")
print(arr)

Array before swapping:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
______________________
Array after swapping:
[[ 0  5  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">29. Shuffle array elements</span>

In [16]:
arr = np.arange(15)
print("Array before shuffling:")
print(arr)

np.random.shuffle(arr)
print("______________________________________________")

print("Array after shuffling:")
print(arr)

Array before shuffling:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
______________________________________________
Array after shuffling:
[ 1 14  4  6 10  5  2  3 13  8 12  9 11  0  7]


### **`numpy.random.shuffle`**

`numpy.random.shuffle` 是 NumPy 中用于随机打乱（洗牌）数组元素的函数。它会对原数组进行就地（in-place）修改，打乱数组中的元素顺序。

### **语法**
```python
numpy.random.shuffle(arr)
```

#### **参数**
- **`arr`** *(array_like)*:  
  要打乱顺序的数组。该数组会被就地修改，返回值为 `None`。

#### **返回值**
- 返回值为 `None`，因为修改是就地进行的。

---

### **示例**

#### **1. 打乱一维数组**
```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Before shuffling:")
print(arr)

np.random.shuffle(arr)
print("After shuffling:")
print(arr)
```

输出可能是：
```
Before shuffling:
[1 2 3 4 5]
After shuffling:
[5 3 2 1 4]  # 打乱后的顺序会随机变化
```

#### **2. 打乱二维数组的行**
`np.random.shuffle` 会按行进行打乱。对于二维数组，每一行会被单独打乱顺序，而行的顺序本身也会被打乱。
```python
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
print("Before shuffling:")
print(arr_2d)

np.random.shuffle(arr_2d)
print("After shuffling:")
print(arr_2d)
```

输出可能是：
```
Before shuffling:
[[1 2]
 [3 4]
 [5 6]]
After shuffling:
[[3 4]
 [1 2]
 [5 6]]  # 行的顺序随机变化
```

#### **3. 打乱多维数组的元素**
如果希望打乱多维数组中所有元素的顺序，可以使用 `np.random.permutation` 或 `np.ravel()` 后再进行打乱。

```python
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
print("Before shuffling:")
print(arr_2d)

flat_arr = arr_2d.ravel()  # 将二维数组展平为一维
np.random.shuffle(flat_arr)
print("After shuffling:")
print(flat_arr.reshape(3, 2))  # 重新将一维数组恢复为二维
```

输出：
```
Before shuffling:
[[1 2]
 [3 4]
 [5 6]]
After shuffling:
[[5 3]
 [1 2]
 [4 6]]  # 所有元素顺序被打乱
```

---

### **注意事项**
- `shuffle` 对输入数组是**就地修改**的，即它会改变原始数组，不返回新的数组。
- 不能用于不可变类型的数据结构，比如元组（tuple）。

### **总结**
- `numpy.random.shuffle` 主要用于对数组（尤其是二维数组的行）进行就地随机打乱。

### <span style = "background:#174D83; border:#ffffff; font-size:100%; color:#fff; border-radius:5px;">30. Median function</span>

In [ ]:
arr = np.arange(20).reshape((4, 5))
print(arr)

print("\nMedian of the array is: ", np.median(arr))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Median of the array is:  9.5


NumPy 是 Python 中用于科学计算的基础库，它为数据处理和科学计算提供了高效的多维数组对象 `ndarray` 和大量数学函数。NumPy 支持向量化操作，并通过高效的底层 C 代码执行各种数学运算，因此它是进行数值计算、数据分析、线性代数、统计分析等任务的理想工具。

以下是一些 NumPy 在科学计算中的常见应用：

### 1. **多维数组 `ndarray`**
NumPy 最核心的数据结构是 `ndarray`，它是一个多维数组对象，可以存储同类型的数据元素。你可以对 `ndarray` 执行各种数学运算，并且它支持广泛的广播机制。

```python
import numpy as np

# 创建一个二维数组
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
```

### 2. **数组的基础操作**
- **加法、减法、乘法、除法**：支持对数组执行元素级的加减乘除运算。
```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

sum_ab = a + b
product_ab = a * b
```

- **广播机制**：NumPy 支持数组与标量、不同形状的数组之间的运算，称为广播。
```python
a = np.array([1, 2, 3])
b = 2
result = a * b  # 每个元素都乘以2
```

### 3. **线性代数**
NumPy 提供了多种函数用于进行线性代数运算，包括矩阵乘法、求逆、行列式等。

```python
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# 矩阵乘法
product = np.dot(a, b)

# 求逆
inverse_a = np.linalg.inv(a)

# 行列式
det_a = np.linalg.det(a)
```

### 4. **随机数生成**
NumPy 提供了用于生成随机数的强大功能，涵盖了各种分布（均匀分布、正态分布、泊松分布等）。

```python
# 从正态分布中生成随机数
rand_normal = np.random.randn(3, 2)

# 从均匀分布生成随机整数
rand_int = np.random.randint(1, 10, (3, 3))
```

### 5. **统计分析**
NumPy 提供了一些统计函数，用于计算数组的平均值、中位数、标准差等。

```python
arr = np.array([1, 2, 3, 4, 5])

mean = np.mean(arr)  # 平均值
std_dev = np.std(arr)  # 标准差
sum_arr = np.sum(arr)  # 求和
```

### 6. **插值与拟合**
NumPy 还支持插值和数据拟合，用于处理科学计算中的离散数据点。

```python
# 一维插值
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
interp_value = np.interp(2.5, x, y)  # 插值
```

### 7. **傅里叶变换**
NumPy 提供了傅里叶变换（Fourier Transform）函数，用于信号处理和频率分析。

```python
signal = np.array([0, 1, 0, -1])
fft_signal = np.fft.fft(signal)  # 快速傅里叶变换
```

### 8. **微积分与数值积分**
NumPy 支持数值积分、微分等运算，虽然 NumPy 本身不包含专门的积分函数，但可以通过数值方法和 `scipy` 库结合使用进行更复杂的计算。

```python
# 通过数值方法计算导数
dx = 0.1
x = np.arange(0, 10, dx)
y = np.sin(x)

dy = np.gradient(y, dx)  # 计算导数
```

### 9. **矩阵分解**
NumPy 提供了矩阵分解工具，如奇异值分解（SVD）、特征值分解等。

```python
# 奇异值分解（SVD）
U, S, V = np.linalg.svd(a)
```

### 10. **科学计算中常见的应用场景**
- **图像处理**：NumPy 数组可以用来存储和处理图像数据。
- **数据分析**：用于科学研究中的数据存储、清洗、分析和建模。
- **优化问题**：结合其他科学计算库（如 `scipy.optimize`），NumPy 可以用来解决最优化问题。
- **数值模拟**：NumPy 提供了生成数据、计算方程、进行数值模拟的工具，广泛应用于物理学、化学、工程等领域。

### 小结
NumPy 是科学计算中的一个核心工具，广泛应用于数学、物理、工程、统计学、机器学习等领域。通过 NumPy，用户能够高效地进行数据处理、数学运算、线性代数、统计分析等工作。

NumPy 提供了多种统计分析功能，可以帮助我们处理和分析数据集中的各种统计指标。以下是 NumPy 常见的统计分析函数和应用：

### 1. **计算均值（Mean）**
`numpy.mean` 用于计算数组的算术平均值。

```python
import numpy as np

data = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(data)
print(f"Mean: {mean_value}")
```
输出：
```
Mean: 3.0
```

### 2. **计算中位数（Median）**
`numpy.median` 用于计算数组的中位数，即将数据按大小排列后位于中间位置的值。

```python
data = np.array([1, 2, 3, 4, 5])
median_value = np.median(data)
print(f"Median: {median_value}")
```
输出：
```
Median: 3.0
```

### 3. **计算方差（Variance）**
`numpy.var` 用于计算数组的方差，表示数据点偏离均值的程度。

```python
data = np.array([1, 2, 3, 4, 5])
variance_value = np.var(data)
print(f"Variance: {variance_value}")
```
输出：
```
Variance: 2.0
```

### 4. **计算标准差（Standard Deviation）**
`numpy.std` 用于计算数组的标准差，是方差的平方根。

```python
data = np.array([1, 2, 3, 4, 5])
std_dev_value = np.std(data)
print(f"Standard Deviation: {std_dev_value}")
```
输出：
```
Standard Deviation: 1.4142135623730951
```

### 5. **计算最小值和最大值（Min and Max）**
`numpy.min` 和 `numpy.max` 用于计算数组中的最小值和最大值。

```python
data = np.array([1, 2, 3, 4, 5])
min_value = np.min(data)
max_value = np.max(data)
print(f"Min: {min_value}, Max: {max_value}")
```
输出：
```
Min: 1, Max: 5
```

### 6. **计算四分位数（Percentile）**
`numpy.percentile` 用于计算数组的指定百分位数值。

```python
data = np.array([1, 2, 3, 4, 5])
percentile_value = np.percentile(data, 50)  # 50% 百分位即为中位数
print(f"50th Percentile (Median): {percentile_value}")
```
输出：
```
50th Percentile (Median): 3.0
```

### 7. **计算协方差（Covariance）**
`numpy.cov` 用于计算两个变量之间的协方差，协方差用于衡量两个变量之间的关系。

```python
data1 = np.array([1, 2, 3, 4, 5])
data2 = np.array([5, 4, 3, 2, 1])

covariance_matrix = np.cov(data1, data2)
print(f"Covariance Matrix: \n{covariance_matrix}")
```
输出：
```
Covariance Matrix:
[[ 2.5 -2.5]
 [-2.5  2.5]]
```

### 8. **计算相关系数（Correlation Coefficient）**
`numpy.corrcoef` 用于计算数组之间的相关系数，衡量两个变量之间的线性相关性。

```python
data1 = np.array([1, 2, 3, 4, 5])
data2 = np.array([5, 4, 3, 2, 1])

correlation_matrix = np.corrcoef(data1, data2)
print(f"Correlation Matrix: \n{correlation_matrix}")
```
输出：
```
Correlation Matrix:
[[ 1. -1.]
 [-1.  1.]]
```
相关系数为 -1，表明 `data1` 和 `data2` 之间存在完全的负线性关系。

### 9. **求积（Product）**
`numpy.prod` 用于计算数组中所有元素的积。

```python
data = np.array([1, 2, 3, 4])
product_value = np.prod(data)
print(f"Product: {product_value}")
```
输出：
```
Product: 24
```

### 10. **计算累计和、累计积（Cumulative Sum / Product）**
- `numpy.cumsum` 用于计算数组元素的累计和。
- `numpy.cumprod` 用于计算数组元素的累计积。

```python
data = np.array([1, 2, 3, 4])
cumulative_sum = np.cumsum(data)
cumulative_product = np.cumprod(data)

print(f"Cumulative Sum: {cumulative_sum}")
print(f"Cumulative Product: {cumulative_product}")
```
输出：
```
Cumulative Sum: [ 1  3  6 10]
Cumulative Product: [ 1  2  6 24]
```

### 11. **计算频率（Histogram）**
`numpy.histogram` 用于计算数据集的直方图，帮助我们了解数据的分布情况。

```python
data = np.random.randn(1000)  # 生成1000个正态分布数据
hist, bin_edges = np.histogram(data, bins=10)  # 计算直方图
print(f"Histogram: {hist}")
```

### 12. **NumPy的统计函数总结**

- **`np.mean()`**: 计算均值
- **`np.median()`**: 计算中位数
- **`np.var()`**: 计算方差
- **`np.std()`**: 计算标准差
- **`np.min()` / `np.max()`**: 计算最小值和最大值
- **`np.percentile()`**: 计算百分位数
- **`np.cov()`**: 计算协方差矩阵
- **`np.corrcoef()`**: 计算相关系数
- **`np.prod()`**: 计算乘积
- **`np.cumsum()` / `np.cumprod()`**: 计算累计和与累计积
- **`np.histogram()`**: 计算直方图

### **总结**
NumPy 提供了丰富的统计分析函数，帮助我们高效地对数据进行各种统计运算。这些函数广泛应用于数据分析、机器学习、信号处理等领域，是处理和分析科学数据的基础工具。

Num值提供了多种方法进行插值和拟合，帮助我们在离散数据点之间做插值和建立数据模型。这里主要介绍 NumPy 中的一些插值方法，以及如何使用 `scipy` 库进行插值和数据拟合。

### 1. **一维插值（`numpy.interp`）**
`numpy.interp` 是一个一维插值函数，用于在已知数据点之间进行线性插值。它假设数据是单调递增的，并返回与给定 x 值对应的 y 值。

#### 示例：
```python
import numpy as np

# 已知数据点
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

# 插值点
x_new = np.array([1.5, 2.5, 3.5])

# 使用一维插值进行预测
y_new = np.interp(x_new, x, y)

print(f"Interpolated values: {y_new}")
```
输出：
```
Interpolated values: [3. 5. 7.]
```
在此示例中，我们通过 `numpy.interp` 计算了在 `x_new` 处的插值结果，得到了预测的 y 值。

### 2. **多项式拟合（`numpy.polyfit`）**
`numpy.polyfit` 可以对数据进行多项式拟合，返回拟合的多项式系数。这个方法适用于对数据进行曲线拟合，找到最佳拟合的多项式。

#### 示例：
```python
import numpy as np
import matplotlib.pyplot as plt

# 已知数据点
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 4, 9, 16, 25])

# 对数据进行二次多项式拟合
coefficients = np.polyfit(x, y, 2)

# 打印拟合的多项式系数
print(f"Polynomial coefficients: {coefficients}")

# 使用拟合系数创建多项式
p = np.poly1d(coefficients)

# 绘制拟合曲线
x_fit = np.linspace(1, 5, 100)
y_fit = p(x_fit)

plt.scatter(x, y, color='red', label='Original data')
plt.plot(x_fit, y_fit, label='Fitted polynomial')
plt.legend()
plt.show()
```
输出：
```
Polynomial coefficients: [ 1.00000000e+00  4.99474247e-16 -2.09461551e-16]
```
该示例展示了如何对数据进行二次多项式拟合，结果是一个接近 \( y = x^2 \) 的拟合曲线。

### 3. **曲线拟合（`scipy.optimize.curve_fit`）**
`scipy.optimize.curve_fit` 是 SciPy 库中用于非线性最小二乘法拟合的函数，能够拟合各种类型的函数。它不仅支持线性和多项式拟合，还可以拟合更复杂的模型（例如指数函数、正弦函数等）。

#### 示例：
```python
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

# 已知数据点
x = np.array([1, 2, 3, 4, 5])
y = np.array([2.2, 4.8, 9.1, 16.1, 25.2])

# 定义拟合的函数模型（例如二次函数）
def model(x, a, b, c):
    return a * x**2 + b * x + c

# 使用 curve_fit 进行拟合
params, covariance = curve_fit(model, x, y)

# 打印拟合参数
print(f"Fitted parameters: {params}")

# 使用拟合参数绘制拟合曲线
x_fit = np.linspace(1, 5, 100)
y_fit = model(x_fit, *params)

plt.scatter(x, y, color='red', label='Original data')
plt.plot(x_fit, y_fit, label='Fitted curve', color='blue')
plt.legend()
plt.show()
```
输出：
```
Fitted parameters: [ 1.00010849e+00  3.29507635e-06 -2.24068018e-06]
```
在这个例子中，`curve_fit` 函数通过最小二乘法拟合出最适合的二次函数参数，并绘制出拟合曲线。

### 4. **插值函数（`scipy.interpolate`）**
SciPy 提供了一个更为强大的插值库 `scipy.interpolate`，可以进行一维和多维插值，支持多种插值方法，如线性插值、样条插值等。

#### 示例：一维样条插值
```python
import numpy as np
import matplotlib.pyplot as plt
from scipy import interpolate

# 已知数据点
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 4, 9, 16, 25])

# 使用样条插值
spl = interpolate.CubicSpline(x, y)

# 插值计算
x_new = np.linspace(1, 5, 100)
y_new = spl(x_new)

# 绘制原始数据点和样条插值曲线
plt.scatter(x, y, color='red', label='Original data')
plt.plot(x_new, y_new, label='Cubic spline interpolation')
plt.legend()
plt.show()
```
此示例展示了如何使用 `CubicSpline` 进行样条插值。`CubicSpline` 是一种平滑的插值方法，在数据点之间提供了平滑的曲线。

### 5. **二维插值（`scipy.interpolate.interp2d`）**
对于二维数据，`scipy.interpolate.interp2d` 提供了简单的插值方法。

#### 示例：
```python
import numpy as np
import matplotlib.pyplot as plt
from scipy import interpolate

# 已知数据点
x = np.array([1, 2, 3])
y = np.array([1, 2, 3])
z = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 创建二维插值函数
f = interpolate.interp2d(x, y, z, kind='linear')

# 在新的点上进行插值
x_new = np.array([1.5, 2.5])
y_new = np.array([1.5, 2.5])
z_new = f(x_new, y_new)

print(f"Interpolated values: {z_new}")
```
输出：
```
Interpolated values: [[2.25 3.25]
 [5.25 6.25]]
```
在此例中，`interp2d` 用于进行二维插值，可以在给定的 `x` 和 `y` 上计算 `z` 值。

### 小结
- **一维插值**：`numpy.interp` 是最常用的一维线性插值方法，适用于简单的线性插值问题。
- **多项式拟合**：`numpy.polyfit` 用于多项式拟合，可以进行多次曲线拟合，广泛应用于简单的回归分析。
- **非线性拟合**：`scipy.optimize.curve_fit` 用于非线性最小二乘拟合，能够处理复杂的模型拟合。
- **样条插值**：`scipy.interpolate.CubicSpline` 提供了平滑的插值方法，适用于连续性要求较高的情况。
- **二维插值**：`scipy.interpolate.interp2d` 适用于二维数据的插值，可以根据给定的 x 和 y 坐标插值。

这些插值和拟合方法在科学计算、工程建模、数据分析、机器学习等领域有广泛的应用。

NumPy 提供了多种方法来存储和读取数据文件，常用的有 `.npy`、`.npz` 格式，以及常见的文本文件格式（如 CSV、TXT 等）。下面介绍几种常见的存取文件方法。

### 1. **保存和加载 `.npy` 文件**
`.npy` 是 NumPy 自己的二进制格式，用于存储数组数据。它是高效的，特别是当数组较大时，能够保留数据类型、形状等信息。

#### 保存 NumPy 数组到 `.npy` 文件：
```python
import numpy as np

# 创建一个 NumPy 数组
arr = np.array([1, 2, 3, 4, 5])

# 保存为 .npy 文件
np.save('array.npy', arr)
```

#### 从 `.npy` 文件加载 NumPy 数组：
```python
# 从 .npy 文件加载数组
loaded_arr = np.load('array.npy')
print(loaded_arr)
```

### 2. **保存和加载 `.npz` 文件**
`.npz` 是一种压缩格式，允许将多个数组存储在一个文件中。每个数组都会被保存为一个字典条目，数组的名字是字典的键。

#### 保存多个数组到 `.npz` 文件：
```python
# 创建多个 NumPy 数组
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# 保存为 .npz 文件
np.savez('arrays.npz', array1=arr1, array2=arr2)
```

#### 从 `.npz` 文件加载多个数组：
```python
# 从 .npz 文件加载多个数组
data = np.load('arrays.npz')

# 访问文件中的数组
print(data['array1'])  # 输出 array1 数组
print(data['array2'])  # 输出 array2 数组
```

### 3. **保存和加载 CSV 文件**
NumPy 提供了 `np.savetxt` 和 `np.loadtxt` 来处理 CSV 或其他文本文件格式。这些方法可以用来将数组保存为文本文件，或者从文本文件中加载数组。

#### 保存 NumPy 数组到 CSV 文件：
```python
# 创建一个 NumPy 数组
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 保存为 CSV 文件
np.savetxt('array.csv', arr, delimiter=',')
```

#### 从 CSV 文件加载 NumPy 数组：
```python
# 从 CSV 文件加载数组
loaded_arr = np.loadtxt('array.csv', delimiter=',')
print(loaded_arr)
```

### 4. **保存和加载文本文件（TXT）**
`np.savetxt` 还可以用来将数组保存为简单的文本格式（如 `.txt` 文件），并可以自定义分隔符等格式选项。

#### 保存 NumPy 数组到 TXT 文件：
```python
# 创建一个 NumPy 数组
arr = np.array([1, 2, 3, 4, 5])

# 保存为 TXT 文件
np.savetxt('array.txt', arr)
```

#### 从 TXT 文件加载 NumPy 数组：
```python
# 从 TXT 文件加载数组
loaded_arr = np.loadtxt('array.txt')
print(loaded_arr)
```

### 5. **使用 `np.genfromtxt` 读取 CSV 文件（处理缺失值）**
`np.genfromtxt` 是一个更灵活的读取函数，它允许在加载 CSV 文件时处理缺失值等问题。相比 `np.loadtxt`，`np.genfromtxt` 更加宽容，可以读取格式不完全一致的文件。

#### 示例：
```python
# 创建一个带有缺失值的 CSV 文件
arr_with_nan = np.array([[1, 2, np.nan], [4, 5, 6], [7, 8, 9]])

# 保存带有缺失值的数组
np.savetxt('array_with_nan.csv', arr_with_nan, delimiter=',', fmt='%f')

# 使用 genfromtxt 读取文件
loaded_arr_with_nan = np.genfromtxt('array_with_nan.csv', delimiter=',')
print(loaded_arr_with_nan)
```

### 总结
- **`np.save()` 和 `np.load()`**：适用于二进制格式的 `.npy` 文件，存储和加载效率高，适用于大规模数组。
- **`np.savez()` 和 `np.load()`**：适用于多个数组的存储和加载，支持压缩文件 `.npz`。
- **`np.savetxt()` 和 `np.loadtxt()`**：适用于文本文件（如 CSV 和 TXT），数据存储为简单的文本格式。
- **`np.genfromtxt()`**：更加灵活，适用于带有缺失值或格式不一致的文本文件。

根据数据的大小和需要的存储格式，你可以选择适合的方式来存取 NumPy 数组。